name: deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  basic_checks:
    name: basic_checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: install bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version-file: .bun_version
      - name: install dependencies
        run: make install
      - name: run ci_checks
        run: make ci_checks

  docker_checks:
    needs: basic_checks
    name: docker_checks_(${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        runner: [
          ubuntu-latest,
          ubuntu-24.04-arm,
          macos-latest,
          macos-13 ]

    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - name: build images
        run: make -C deployment docker_build

      - name: test images
        run: make -C deployment docker_test
